### GET / route

GET http://localhost:3000/
Content-Type: application/json

### GET users

GET http://localhost:3000/user
Content-Type: application/json

### GET one user

GET http://localhost:3000/user/1
Content-Type: application/json

### POST User

POST http://localhost:3000/user
Content-Type: application/json

{
    "id": 0,
    "name": "Termesz2",
    "email": "termeszvok2@gmail.com",
    "password": "termike1234."
}

### DELETE user

DELETE http://localhost:3000/user/4
Content-Type: application/json

### PATCH user by id
PATCH http://localhost:3000/user/1
Content-Type: application/json

{
    "name": "Termesz2",
    "age": 25,
    "gender": "male"
}